$schema: node_modules/@cspell/cspell-types/cspell.schema.json
allowCompoundWords: true
useGitignore: true
ignorePaths: []
words:
  - Acura
  - Choudhury
  - cmdk
  - Dinuka
  - Fisker
  - ianvs
  - Infiniti
  - kabeiri
  - Khurshid
  - Koenigsegg
  - nums
  - oklch
  - Pagani
  - Ranasinghe
  - Salma
  - shadcn
  - Supasbase
  - Zaker
