$schema: node_modules/@cspell/cspell-types/cspell.schema.json
allowCompoundWords: true
useGitignore: true
ignorePaths: []
words:
  - Choudhury
  - cmdk
  - Dinuka
  - ianvs
  - kabeiri
  - Khurshid
  - nums
  - oklch
  - Ranasinghe
  - Salma
  - Supasbase
  - Zaker
