import { z } from "zod";

export const carFormSchema = z.object({
  make: z.string().min(1, "Make must be at least 1 characters"),
  model: z.string().min(1, "Model must be at least 1 characters"),
  year: z.string().min(1, "Year is required"),
  color: z.string(),
  miles: z.string(),
  licensePlate: z.string().min(1, "License plate is required"),
});

export type carFormSchema = z.infer<typeof carFormSchema>;

export const carMakerList = [
  "Acura",
  "Alfa Romeo",
  "Ariel",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Bugatti",
  "Buick",
  "Cadillac",
  "Caterham",
  "Chevrolet",
  "Chrysler",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Fisker",
  "Ford",
  "Genesis",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Koenigsegg",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Lotus",
  "Lucid",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "Mini",
  "Mitsubishi",
  "Morgan",
  "Nissan",
  "Noble",
  "Other",
  "Pagani",
  "Polestar",
  "Porsche",
  "Ram",
  "Rivian",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "TVR",
  "Volkswagen",
  "Volvo",
];
